name: ProjectPlugin
version: '${project.version}'
main: io.github.m1gw.projectplugin.ProjectPlugin
api-version: '1.20'
author: gw & black_2
description: A plugin for the pvp event


commands:
  gotospawn:
    description: Allows players to go to spawn or send others to spawn
    usage: /<command> ([player])
    permission: projectplugin.admin
  addnewpeopletogame:
    description: Allows/Forbid players to join participants in the game when joined
    usage: /addnewpeopletogame true/false
    permission: projectplugin.admin
  battle:
    description: Allows players to start a battle
    usage: /battle
    permission: projectplugin.admin
  givewinnersplaying:
    description: gives the currentlyplaying team to all winners
    usage: /givewinnersplaying
    permission: projectplugin.admin
  decide:
    description: decide what to do when a player disconnects
    usage: /decide
    permission: projectplugin.admin

permissions:
  admin:
    description: admin
    default: op
